services:
  main-app:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        INSTALL_DEV: "true"
    container_name: main-app
    ports:
      - "8000:8000"
    command: "sh /entrypoint.sh"
    volumes:
      - ..:/app
    env_file:
      - ../.env
