services:
  postgres:
    image: postgres:17rc1-alpine
    command: >
      sh -c '
      apk add --no-cache postgresql-contrib &&
      docker-entrypoint.sh postgres
      '
    environment:
      POSTGRES_DB: ${APP_CONFIG__DATABASE__db_name}
      POSTGRES_USER: ${APP_CONFIG__DATABASE__user}
      POSTGRES_PASSWORD: ${APP_CONFIG__DATABASE__password}
    container_name: postgresql-container
    ports:
      - "${APP_CONFIG__DATABASE__external_port}:5432"
    volumes:
      - postgresql_data_chimney:/var/lib/postgresql/data
      - ../init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ../.env

volumes:
  postgresql_data_chimney:
