"""'dts'

Revision ID: 52da907a3b43
Revises: 8dda93c23692
Create Date: 2025-04-22 21:04:51.425108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52da907a3b43'
down_revision: Union[str, None] = '8dda93c23692'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_order_items_order_id', 'order_items', type_='unique')
    op.add_column('orders', sa.Column('price_discount', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'price_discount')
    op.create_unique_constraint('uq_order_items_order_id', 'order_items', ['order_id'])
    # ### end Alembic commands ###
