"""'dts'

Revision ID: 9ed8c55db68c
Revises: d3d0a6082209
Create Date: 2025-04-22 23:11:48.192238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ed8c55db68c'
down_revision: Union[str, None] = 'd3d0a6082209'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_orderitems_product_id', 'orderitems', type_='unique')
    op.create_unique_constraint('uq_orderitems_order_id_product_id', 'orderitems', ['order_id', 'product_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_orderitems_order_id_product_id', 'orderitems', type_='unique')
    op.create_unique_constraint('uq_orderitems_product_id', 'orderitems', ['product_id'])
    # ### end Alembic commands ###
