"""'dts'

Revision ID: 6fa4b55e8323
Revises: aac4560d070a
Create Date: 2025-05-18 12:01:00.693526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fa4b55e8323'
down_revision: Union[str, None] = 'aac4560d070a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('waybill_number', sa.String(length=30), nullable=True))
    op.create_unique_constraint(op.f('uq_orders_waybill_number'), 'orders', ['waybill_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_orders_waybill_number'), 'orders', type_='unique')
    op.drop_column('orders', 'waybill_number')
    # ### end Alembic commands ###
