"""'dts'

Revision ID: 8be1b8f1e1df
Revises: c41dbceb88fc
Create Date: 2025-04-27 21:44:36.419526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8be1b8f1e1df'
down_revision: Union[str, None] = 'c41dbceb88fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uniqueproducts',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_uniqueproducts_category_id_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uniqueproducts')),
    sa.UniqueConstraint('slug', name=op.f('uq_uniqueproducts_slug'))
    )
    op.create_index(op.f('ix_uniqueproducts_id'), 'uniqueproducts', ['id'], unique=False)
    op.create_table('productvariations',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_percentage', sa.Integer(), server_default='0', nullable=False),
    sa.Column('diameter', sa.String(length=20), nullable=True),
    sa.Column('length', sa.String(length=20), nullable=True),
    sa.Column('thickness', sa.String(length=20), nullable=True),
    sa.Column('angle', sa.String(length=20), nullable=True),
    sa.Column('metal_type', sa.String(length=20), nullable=True),
    sa.Column('extra_attrs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('discount_percentage >= 0 AND discount_percentage <= 100', name=op.f('ck_productvariations_discount_range')),
    sa.ForeignKeyConstraint(['product_id'], ['uniqueproducts.id'], name=op.f('fk_productvariations_product_id_uniqueproducts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_productvariations'))
    )
    op.create_index(op.f('ix_productvariations_id'), 'productvariations', ['id'], unique=False)
    op.drop_constraint('fk_cartitems_product_id_products', 'cartitems', type_='foreignkey')
    op.create_foreign_key(op.f('fk_cartitems_product_id_productvariations'), 'cartitems', 'productvariations', ['product_id'], ['id'])
    op.drop_constraint('fk_likes_product_id_products', 'likes', type_='foreignkey')
    op.create_foreign_key(op.f('fk_likes_product_id_productvariations'), 'likes', 'productvariations', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_orderitems_product_id_products', 'orderitems', type_='foreignkey')
    op.create_foreign_key(op.f('fk_orderitems_product_id_productvariations'), 'orderitems', 'productvariations', ['product_id'], ['id'])
    op.drop_constraint('fk_productimages_product_id_products', 'productimages', type_='foreignkey')
    op.create_foreign_key(op.f('fk_productimages_product_id_uniqueproducts'), 'productimages', 'uniqueproducts', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_productimages_product_id_uniqueproducts'), 'productimages', type_='foreignkey')
    op.create_foreign_key('fk_productimages_product_id_products', 'productimages', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_orderitems_product_id_productvariations'), 'orderitems', type_='foreignkey')
    op.create_foreign_key('fk_orderitems_product_id_products', 'orderitems', 'products', ['product_id'], ['id'])
    op.drop_constraint(op.f('fk_likes_product_id_productvariations'), 'likes', type_='foreignkey')
    op.create_foreign_key('fk_likes_product_id_products', 'likes', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_cartitems_product_id_productvariations'), 'cartitems', type_='foreignkey')
    op.create_foreign_key('fk_cartitems_product_id_products', 'cartitems', 'products', ['product_id'], ['id'])
    op.drop_index(op.f('ix_productvariations_id'), table_name='productvariations')
    op.drop_table('productvariations')
    op.drop_index(op.f('ix_uniqueproducts_id'), table_name='uniqueproducts')
    op.drop_table('uniqueproducts')
    # ### end Alembic commands ###
