"""'dts'

Revision ID: 7a0c250115ba
Revises: 09c90416771e
Create Date: 2025-03-22 16:07:31.701710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a0c250115ba'
down_revision: Union[str, None] = '09c90416771e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_cartitems_cart_id_carts', 'cartitems', type_='foreignkey')
    op.create_foreign_key(op.f('fk_cartitems_cart_id_carts'), 'cartitems', 'carts', ['cart_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_cartitems_cart_id_carts'), 'cartitems', type_='foreignkey')
    op.create_foreign_key('fk_cartitems_cart_id_carts', 'cartitems', 'carts', ['cart_id'], ['id'])
    # ### end Alembic commands ###
