"""'dts'

Revision ID: c41dbceb88fc
Revises: 2330e134c005
Create Date: 2025-04-23 14:43:20.495415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c41dbceb88fc'
down_revision: Union[str, None] = '2330e134c005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_orderitems_order_id_orders', 'orderitems', type_='foreignkey')
    op.create_foreign_key(op.f('fk_orderitems_order_id_orders'), 'orderitems', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_orderitems_order_id_orders'), 'orderitems', type_='foreignkey')
    op.create_foreign_key('fk_orderitems_order_id_orders', 'orderitems', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###
