"""'dts'

Revision ID: 19376abfab08
Revises: 7a0c250115ba
Create Date: 2025-03-29 13:40:15.991786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19376abfab08'
down_revision: Union[str, None] = '7a0c250115ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('discount_percentage', sa.Integer(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'discount_percentage')
    # ### end Alembic commands ###
