"""'dts'

Revision ID: d3d0a6082209
Revises: 52da907a3b43
Create Date: 2025-04-22 22:29:58.272418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd3d0a6082209'
down_revision: Union[str, None] = '52da907a3b43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orderitems',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_at_order', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_orderitems_order_id_orders')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_orderitems_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orderitems')),
    sa.UniqueConstraint('product_id', name=op.f('uq_orderitems_product_id'))
    )
    op.create_index(op.f('ix_orderitems_id'), 'orderitems', ['id'], unique=False)
    op.drop_index('ix_order_items_id', table_name='order_items')
    op.drop_table('order_items')
    op.alter_column('orders', 'shipping_method',
               existing_type=postgresql.ENUM('self_pickup', 'courier', 'nova_poshta', 'ukrposhta', name='shippingmethod'),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('orders', 'payment_method',
               existing_type=postgresql.ENUM('cash', 'card', 'paypal', name='paymentmethod'),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('orders', 'status',
               existing_type=postgresql.ENUM('pending', 'processing', 'shipped', 'delivered', 'canceled', name='orderstatus'),
               type_=sa.String(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'status',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('pending', 'processing', 'shipped', 'delivered', 'canceled', name='orderstatus'),
               existing_nullable=False)
    op.alter_column('orders', 'payment_method',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('cash', 'card', 'paypal', name='paymentmethod'),
               existing_nullable=False)
    op.alter_column('orders', 'shipping_method',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('self_pickup', 'courier', 'nova_poshta', 'ukrposhta', name='shippingmethod'),
               existing_nullable=False)
    op.create_table('order_items',
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price_at_order', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='fk_order_items_order_id_orders'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='fk_order_items_product_id_products'),
    sa.PrimaryKeyConstraint('id', name='pk_order_items'),
    sa.UniqueConstraint('product_id', name='uq_order_items_product_id')
    )
    op.create_index('ix_order_items_id', 'order_items', ['id'], unique=False)
    op.drop_index(op.f('ix_orderitems_id'), table_name='orderitems')
    op.drop_table('orderitems')
    # ### end Alembic commands ###
