"""'dts'

Revision ID: 09c90416771e
Revises: 677624e1144b
Create Date: 2025-03-22 16:00:40.088305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09c90416771e'
down_revision: Union[str, None] = '677624e1144b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('carts', 'session_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=47),
               existing_nullable=True)
    op.create_unique_constraint(op.f('uq_carts_session_id'), 'carts', ['session_id'])
    op.create_unique_constraint(op.f('uq_carts_user_id'), 'carts', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_carts_user_id'), 'carts', type_='unique')
    op.drop_constraint(op.f('uq_carts_session_id'), 'carts', type_='unique')
    op.alter_column('carts', 'session_id',
               existing_type=sa.String(length=47),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
    # ### end Alembic commands ###
