"""'dts'

Revision ID: c6e75ee1c782
Revises: 6fa4b55e8323
Create Date: 2025-05-27 17:48:40.513770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6e75ee1c782'
down_revision: Union[str, None] = '6fa4b55e8323'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('file_path', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'file_path')
    # ### end Alembic commands ###
