"""dts

Revision ID: c6761f39d657
Revises: e3a1c7f9b2d4
Create Date: 2026-04-11 08:49:17.456586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6761f39d657'
down_revision: Union[str, None] = 'e3a1c7f9b2d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('comment', sa.String(length=500), nullable=True))
    op.add_column('orders', sa.Column('internal_comment', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'internal_comment')
    op.drop_column('orders', 'comment')
    # ### end Alembic commands ###
