"""dts

Revision ID: cc6c6a3dac90
Revises: 5b90fd80e1b6
Create Date: 2026-04-26 21:00:46.661442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc6c6a3dac90'
down_revision: Union[str, None] = '5b90fd80e1b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productvariations', sa.Column('discount_sort_order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productvariations', 'discount_sort_order')
    # ### end Alembic commands ###
