"""dts

Revision ID: 6200a653fc10
Revises: cc6c6a3dac90
Create Date: 2026-05-01 21:04:17.293884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6200a653fc10'
down_revision: Union[str, None] = 'cc6c6a3dac90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('website_settings', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('website_settings', sa.Column('email', sa.String(length=150), nullable=True))
    op.add_column('website_settings', sa.Column('address', sa.String(length=300), nullable=True))
    op.add_column('website_settings', sa.Column('work_schedule', sa.String(length=200), nullable=True))
    op.add_column('website_settings', sa.Column('telegram_url', sa.String(length=300), nullable=True))
    op.add_column('website_settings', sa.Column('facebook_url', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('website_settings', 'facebook_url')
    op.drop_column('website_settings', 'telegram_url')
    op.drop_column('website_settings', 'work_schedule')
    op.drop_column('website_settings', 'address')
    op.drop_column('website_settings', 'email')
    op.drop_column('website_settings', 'phone')
    # ### end Alembic commands ###
