"""dts

Revision ID: 6b6a52fd7be5
Revises: c6761f39d657
Create Date: 2026-04-26 15:24:27.004682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b6a52fd7be5'
down_revision: Union[str, None] = 'c6761f39d657'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('website_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturer_discount', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False),
    sa.Column('seller_markup', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_website_settings'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('website_settings')
    # ### end Alembic commands ###
