"""dts

Revision ID: 5b90fd80e1b6
Revises: 6b6a52fd7be5
Create Date: 2026-04-26 19:24:46.510433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b90fd80e1b6'
down_revision: Union[str, None] = '6b6a52fd7be5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orderitems', sa.Column('product_name', sa.String(length=200), server_default='', nullable=False))
    op.add_column('orderitems', sa.Column('product_slug', sa.String(length=255), server_default='', nullable=False))
    op.add_column('orderitems', sa.Column('product_image', sa.String(length=500), nullable=True))
    op.add_column('orderitems', sa.Column('product_price', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False))
    op.alter_column('orderitems', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('uq_orderitems_order_id_product_id', 'orderitems', type_='unique')
    op.drop_constraint('fk_orderitems_product_id_productvariations', 'orderitems', type_='foreignkey')
    op.create_foreign_key(op.f('fk_orderitems_product_id_productvariations'), 'orderitems', 'productvariations', ['product_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_orderitems_product_id_productvariations'), 'orderitems', type_='foreignkey')
    op.create_foreign_key('fk_orderitems_product_id_productvariations', 'orderitems', 'productvariations', ['product_id'], ['id'])
    op.create_unique_constraint('uq_orderitems_order_id_product_id', 'orderitems', ['order_id', 'product_id'])
    op.alter_column('orderitems', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('orderitems', 'product_price')
    op.drop_column('orderitems', 'product_image')
    op.drop_column('orderitems', 'product_slug')
    op.drop_column('orderitems', 'product_name')
    # ### end Alembic commands ###
